### ISSUE TITLE
Alessia Cavallari AC Graphic Sportswear

### ISSUE THREAD

**Issue by alessiaacavallari** [matteobaccan/ACME-2023-2024-WebDesign#12]
https://github.com/alessiaacavallari/Sito-web

**Comment by matteobaccan** [comment]
Ho guardato il progetto
- La pagina di readme.md è impostata bene, mi aspetto un suo completamento mano a meno che vai vanti col progetto
- Mandami anche il link a Netlify in modo ad iniziare a vedere la pubblicazione

**Comment by alessiaacavallari** [comment]
https://splendorous-pixie-122546.netlify.app/

Il giorno lun 29 gen 2024 alle ore 12:19 Matteo Baccan <
***@***.***> ha scritto:
