### ISSUE TITLE
progetto esame Marina Matilde

### ISSUE THREAD

**Issue by Mat01ty** [matteobaccan/ACME-2023-2024-WebDesign#36]
https://github.com/Mat01ty/Archivio.git
https://chipper-semifreddo-0743e1.netlify.app/

**Comment by matteobaccan** [comment]
Ciao

i link vanno bene.
Mi aspetto una sistemazione dei contenuti del progetto GitHub: inizia a sistemare almeno il readme.md

Prendi ispirazione da questo https://github.com/matteobaccan/github-netlify-boilerplate/blob/main/README.md
